# 🐾 @noel/paw: Paw is a personalized website about myself and my projects, source code for https://floofy.dev
# Copyright (c) 2018-2022 Noel
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: ESLint
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.husky/**'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'package.json'
      - 'renovate.json'
      - 'tsconfig.json'

  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.husky/**'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'package.json'
      - 'renovate.json'
      - 'tsconfig.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Uses Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Setup Yarn and node-modules cache
        id: yarn-cache
        uses: auguwu/node-pm-action@master

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' || steps.yarn-cache.outputs.node-modules-cache-hit != 'true'
        run: yarn install --immutable

      - name: Lint project with ESLint
        run: yarn lint

      - name: Check if project compiles
        run: tsc --noEmit
