name: ESLint
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.husky/**'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'package.json'
      - 'renovate.json'
      - 'tsconfig.json'

  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.husky/**'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'package.json'
      - 'renovate.json'
      - 'tsconfig.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Uses Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installs ESLint globally
        run: npm i -g eslint

      - name: Installs all local dependencies
        run: npm i

      - name: Lints the repository for any code-checking errors
        run: npm run lint
